// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADs1OSmUoaiXnRFqf0B2GdDVP3AwT60pY',
    appId: '1:167084435015:android:d355d1d017074b5c59b362',
    messagingSenderId: '167084435015',
    projectId: 'my-first-firebase-app-b87bf',
    storageBucket: 'my-first-firebase-app-b87bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_2K3pWYurqcfSJCmcGcFhJZAtxx3Sx3I',
    appId: '1:167084435015:ios:ee7702bf7cfcc32759b362',
    messagingSenderId: '167084435015',
    projectId: 'my-first-firebase-app-b87bf',
    storageBucket: 'my-first-firebase-app-b87bf.appspot.com',
    iosClientId: '167084435015-8dplnr48580rvgh6edvcatljqvgr2na0.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
